yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('justpage/', views.JustStaticPage.as_view()),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]
handler404 = 'core.views.page_not_found'

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
handler403csrf = 'core.views.csrf_failure'
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from core.models import CreatedModel, PubDateModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(verbose_name='Заголовок',
                             max_length=200,
                             help_text='Название группы')
    slug = models.SlugField(
        verbose_name='Уникальный адрес страницы',
        unique=True, help_text=(
            'Укажите уникальный адрес для страницы задачи. Используйте только '
            'латиницу, цифры, дефисы и знаки подчёркивания'))
    description = models.TextField(verbose_name='Описание',
                                   max_length=400,
                                   help_text='Опишите группу')

    def __str__(self):
        return self.title


class Post(PubDateModel):
    text = models.TextField(verbose_name='Текст',
                            help_text='Напишите текст')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Никнейм автора')
    group = models.ForeignKey(Group,
                              on_delete=models.SET_NULL,
                              blank=True,
                              null=True,
                              related_name='posts',
                              verbose_name='Группа',
                              help_text='Название группы')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Картинка'
    )

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments')
    text = models.TextField('Текст', help_text='Текст нового комментария')


class Follow(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Никнейм автора'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Никнейм подписчика'
    )


class Meta:
    ordering = ('-pub_date',)
    verbose_name = 'Пост'
    verbose_name_plural = 'Посты'
    contreins = [
        models.CheckConstraint(
            name='Check follow',
            check=models.Q(models.F('author') != models.F('user'))),
        models.UniqueConstraint(
            name="Проверка единственности подписки",
            fields=["user", "author"],
        ),
    ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        LANGUAGE_CODE = "ru"
        model = Post
        fields = ['group', 'text', 'image']
        widget = {
            'text': forms.Textarea(attrs={'cols': 40, 'rows': 10})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        LANGUAGE_CODE = "ru"
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }
        help_texts = {
            'text': 'Текст нового комментария',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.views.generic.base import TemplateView

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


class JustStaticPage(TemplateView):
    template_name = 'app_name/just_page.html'


def profile(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    count = post_list.count()
    follow = (request.user.is_authenticated
              and Follow.objects.filter(user=user, author=author))
    context = {
        'follow': follow,
        'page_obj': page_obj,
        'author': author,
        'count': count,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    count = post.author.posts.count()
    form = CommentForm(request.POST or None)
    page_comments = Comment.objects.filter(post_id=post_id)
    if request.method == 'POST':
        if form.is_valid():
            Comment.objects.create(
                author=request.user,
                text=form.cleaned_data['text'],
            )
    context = {
        'page_comments': page_comments,
        'post': post,
        'form': form,
        'count': count
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST or None, files=request.FILES or None,)
        if form.is_valid():
            Post.objects.create(
                author=request.user,
                text=form.cleaned_data['text'],
                group=form.cleaned_data['group'],
                image=form.cleaned_data['image']
            )

            return redirect('posts:profile', request.user)
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(
        request,
        'posts/create_post.html',
        {'is_edit': is_edit, 'form': form, 'post': post},
    )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    follow_exist = Follow.objects.filter(user=user, author=author)
    if user != author and follow_exist.count() == 0:
        Follow.objects.create(user=user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=user, author=author).delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_comments.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in page_comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
      {% include 'includes/paginator.html' %}
    </div>

{% endfor %} 

yatube/templates/posts/create_post.html
<!DOCTYPE html> 
<html lang="ru">
{% extends 'base.html' %}
{% load thumbnail %}
{%block title %}
{% if is_edit %}
Редактировать пост
{% else %}
Добавить пост
{% endif %}
{% endblock title %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
              {% if is_edit %}
              Редактировать пост
              {% else %}
              Добавить пост
              {% endif %}               
          </div>
          <div class="card-body"> 
  {% if form.errors %}
  {% for field in form %} 
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
  {% endif %}
   <form method="post" enctype="multipart/form-data">
    {% load user_filters %}
      {% csrf_token %}
        {% for field in form %} 
         <div class="col-md-12 p-6">
          <label for="{{ field.id_for_label }}">
           {{ field.label }}
            {% if field.field.required %}
             <span class="required text-danger">*</span>
             {% endif %}
           </label>
           {{ field|addclass:'form-control' }}
            {% if field.help_text %}
             <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }} 
              </small>
            {% endif %}
          </div>
        {% endfor %}
        <small id="id_group-help" class="form-text text-muted">
          Группа, к которой будет относиться пост
        </small>
                  <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                       Сохранить
                        {% else %}
                         Добавить
                        {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/follow.html
<!DOCTYPE html> 
<html lang="ru">
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{%block title %}Подписки{% endblock title %}
{% block content %}
{% include 'includes/switcher.html' %}
  <div class="container py-5">
    {% for post in page_obj %}
    <ul>
      <li>
        <a href="{% url 'posts:profile' post.author.username %}">Автор: {{ post.author.get_full_name }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div> 
  {% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{%block title %}Записи сообщества {{group.title}}{% endblock title %}
{% block content %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1>{{group.title}}</h1>
    <hr>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{post.pub_date|date:"d E Y"}}
        </li>
      </ul>      
      <p>{{ post.text }}</p>        
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
    <!-- под последним постом нет линии -->
  </div>
{% endblock %}

yatube/templates/posts/index.html
<!DOCTYPE html> 
<html lang="ru">
{% extends 'base.html' %}
{% load thumbnail %}
{%block title %}Последние обновления на сайте{% endblock title %}
{% block content %}
{% include 'includes/switcher.html' %}
  <div class="container py-5">
    {% for post in page_obj %}
    <ul>
      <li>
        <a href="{% url 'posts:profile' post.author.username %}">Автор: {{ post.author.get_full_name }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div> 
  {% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост{{ post.text|truncatechars:30 }}</title>
{% endblock %}
    {% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
              <li class="list-group-item">
                Группа: {{ post.group}}
                {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                {% endif %}
              </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{ count }} 
            </li>
            <li class="list-group-item">
              {% if post.author %}
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
              {% endif %}
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
        </article>
        {% include 'includes/paginator.html' %}
        {% include 'posts/create_comments.html' %} 
      </div> 
      
    {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">    
        <h1>Все посты пользователя {{ author }} </h1>
        <h3>Всего постов: {{ count }} </h3>
        {% if request.user.is_authenticated and follow.count != 0  %}
            <a
            class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
              >
              Отписаться
              </a>
            {% else %}
              <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
          Подписаться
          </a>
          {% endif %}
        {% for post in page_obj %}   
        <article>
          <ul>
            <li>
              Автор: {{ author }}
              <a href="">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
          {{ post.text }}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}    
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>       
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}  
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
  {% endblock %} 